### ISSUE TITLE
Végétation 2016-2017

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#10]

**Comment by marie-pierre-varin** [comment]
@glaroc What's going on here?

**Comment by marie-pierre-varin** [comment]
@francis-lessard @lanch2022 @anouksimard TEST

**Comment by glaroc** [comment]
Ces données avaient déjà été injectées pas Steve, mais j'imagine qu'elles devront être ré-injectées ? . Dans le fichier compilation V7, il y a des valeurs pour la colonne "Recouvrement_pourcent" qui sont de 0.01 ou 0.25, et d'autres qui sont visiblement sur 100 (40, 60, ...). Est-ce que ce sont tous des pourcentages? Est-ce que 0.01 veut dire 0.01% ou 1 % ?  @lanch2022
