### ISSUE TITLE
Cron to clean `taxa_obs`

### ISSUE THREAD

**Issue by vincent-beauregard-ielab** [ReseauBiodiversiteQuebec/Coleo_DB#114]
Some `taxa_obs` becomes detached from observations.

Leaving them may affect expected results using taxa_obs. A regularly executed function should clean unused `taxa_obs` rows.

* [ ] List tables with foreign key to taxa_obs
* [x] Delete records not referenced
* [x] Cron job to execute function every week
* [ ] Make sure lookups have cascade on delete (taxa_ref, taxa_group, taxa_vernacular)

**Comment by vcameron1** [comment]
No need of cascades because `clean_taxa_obs` will always be called right before `refresh_taxa_vernacular` and `refresh_taxa_ref` which delete all content of taxa_ref, taxa_vernacular and lookup tables.
