### ISSUE TITLE
🐛 Introduire la correspondance du best_ref avec les taxons parents dans `api.taxa`

### ISSUE THREAD

**Issue by vcameron1** [ReseauBiodiversiteQuebec/Coleo_DB#125]
`api.taxa` mélange différentes sources pour combler sa taxonomie, ce qui entraine des erreurs lorsqu'il y a synonimie.  Le rang du best_ref doit être conservé dans l'élaboration de api.taxa.

**Comment by vcameron1** [comment]
- [ ] Générer une CTE `best_ref_taxo` pour contenir la taxonomie par source
- [ ] Identifier la best_ref (par priorité de source)
- [ ] Identifier le rang
- [ ] combler la taxonomie avec les parents des références au même rang

**Comment by vincent-beauregard-ielab** [comment]
* Valider si vernaculaire, valid_scientific_name et parents correspondent bien

**Comment by vcameron1** [comment]
Devrait être fixé par l'utilisation de `parent_taxa_name`
