### ISSUE TITLE
Taxonomie : noms vernaculaires partagés parmis plusieurs orthoptères

### ISSUE THREAD

**Issue by vcameron1** [ReseauBiodiversiteQuebec/Coleo_DB#141]
## TODO

- Vernacular ne respecte pas le rang du best_ref
- Byoquel (top priorité vernaculaire) match plusieurs taxons avec 'Nardie bilobée'

```sql
select * from api.taxa where vernacular_fr ilike '%nardie%';
```

### UPDATE

'Nardie bilobée' est le nom taxonomique du taxon `Nardia insecta Lindb.`. Ça peut être le `insecta` qui match avec tous les insectes grâce au fuzzy matching

**Comment by glaroc** [comment]
*orthoptères, pas chauves-souris

**Comment by vcameron1** [comment]
Solution projetée : modif à `api.taxa` pour conserver le taxa_rank dans `vernacular_fr` et `vernacular_en` (comme dans la taxo complète)

**Comment by vcameron1** [comment]
Retirer les noms vernaculaires lorsque pas de match direct ?
