### ISSUE TITLE
Décomposition MO 2023

### ISSUE THREAD

**Issue by francis-lessard** [ReseauBiodiversiteQuebec/Coleo_DB#149]
Les données AGOL sont complètes. La version finale du fichier est disponible ici:

\\sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Decomposition_MO\AGOL\2023\Data

Il se nomme "Decomp_MO_23jan2024_AGOL_VF".

Les données brutes se trouvent ici:

\\sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Decomposition_MO\AGOL\2023\Data\Brute

Les sachets de thé ont été pesé à la mi-décembre 2023. Le fichier des poids se trouve ici:

\\sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Decomposition_MO\Poids

Il se nomme "Sachet_The_2023".

La dernière personne qui s'est occupé de cet indicateur est Nicolas Poirier. Il faut revoir ses notes pour connaitre les étapes à faire avant d'intégrer ces données dans le gabarait d'injection de Coleo.

**Comment by francis-lessard** [comment]
@Lauramilliard
Les données provenant d'AGOL sont prêtes à être intégrées dans le gabarit d'injection. Le fichier contenant ces données se trouvent ici:
\sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Decomposition_MO\AGOL\2022\Data
Le fichier se nomme "Decomp_MO_23jan2024_AGOL_VF".

Les poids des sachets de thé ont été comptabilisés et sont prêts à être intégrés dans le gabarit d'injection. Le fichier contenant ces données se trouvent ici: \sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Decomposition_MO\Poids
Le fichier se nomme "Sachet_The_2023".

**Comment by Lauramilliard** [comment]
Les données ont été saisies dans le gabarit et sont prêtes à l'injection avec les données 2023, mais les cellules et sites 2023 doivent être injectés avant.
