### ISSUE TITLE
ADNe poissons 2016 à 2019

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#17]

**Comment by vcameron1** [comment]
Les données à injecter consistent d'un nombre de séquences (observation) brute par espèces par station (landmark). Les données à injecter incluent aussi un nombre de séquences brute et corrigé par espèces par site (plusieurs stations agrégées). 

***Modifications proposées à coleo***
Ce qui est proposé pour accommoder cette structure particulière des données est de modifier la table obs_edna de façon à ce qu'un landmarks_id soit associé qu'aux observations faites aux stations, qu'il n'y ait pas de landmark pour les observations au site et qu'une colonne précise l'échelle spatiale d'appartenance de la donnée (landmark ou site) pour pouvoir choisir laquelle utiliser lors de l'extraction.

Aussi, il a été proposé d'ajouter une colonne pour le nombre de séquences corrigées.
