### ISSUE TITLE
Acoustique chiroptères 2016-2020

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#20]

**Comment by marie-pierre-varin** [comment]
@Lauramilliard Selon Anouk, ces données sont presque prêtes à être injecter. Pourrais-tu vérifier stp? Merci!

**Comment by JoelleSpooner** [comment]
Grandes lignes des corrections et du nettoyage qui ont été faits sur cette base de données.
- Ajustements de différentes typos, notamment dans les noms de cellules, les numéros de sites et les codes acoustiques.
- Corrections de certaines erreurs au niveau de quel appareil acoustique était associé à quel site. Certaines données avaient été mélangées entre les sites lors de l'identification et il a été possible de faire les corrections en sachant quels appareils acoustiques étaient déployés dans quels sites.
- Ajustement de certaines dates de début et de fin de campagne. Cette information était issue des feuilles de données terrain, cependant, il est arrivé pour certain site que la date de début de campagne (la date où l'appareil est installé) venait après le premier enregistrement acoustique ou encore que le dernier enregistrement acoustique venait après la date de fin de la campagne.
- Enlever les doublons pour ne pas retrouver deux fois la même espèce dans un enregistrement. 
- Uniformisation de la saisie afin de ne pas avoir plusieurs versions d'entrées qui veulent dire la même chose (ex. tourbiere et tourbière)

**Comment by vcameron1** [comment]
Notes pour l'injection des données acoustiques
J'ai préparé le document injection_notes/chiroptera/Acoustique_Injection_VF.xlsx pour l'injection. J'ai effectué les modifications dans le script [injection_acoustique_2016-2020.R](https://github.com/ReseauBiodiversiteQuebec/injection_notes/blob/c72d02408ea35141196e4ec2a68373be36daf7d4/chiroptera/injection_acoustique_2016-2020.R) qui retourne le jeu de données formaté. J'ajoute ci-bas un compte rendu des modifications faites et des données à vérifier.

Données à vérifier
- [ ]  "Noise" est un nom de taxon ?

Colonnes manquantes
- [ ] ref_taxa_rank : https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/461c0c9d473dac8ad5e1c2286bc211214e937f66/API-coleo.md?plain=1#L288
- [ ] ref_taxa_category = "mammifères" (https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/461c0c9d473dac8ad5e1c2286bc211214e937f66/API-coleo.md?plain=1#L289)
- [ ] campaign_technician_1
- [ ] observation_date (pour l'instant, j'ai pris la date dans "obs_id")
- [ ] observation_is_valid = TRUE
- [ ] observation_variable = "présence"
- [ ] ref_taxa_tsn (NE PAS SE FIER AU SCRIPT! L'IDENTIFICATION DOIT ÊTRE VÉRIFIÉE INDIVIDUELLEMENT)

Colonnes à retirer
- [ ] name_cells
- [ ] cell_id
- [ ] type_sites
- [ ] obs_id (a moins que ce soit une donnée importante?)

**Comment by vcameron1** [comment]
Correction des sites 127_116_H01, 127_116_H02, 127_116_F01  à 126_116.
