### ISSUE TITLE
Niveau d'Eau marais - profondeur et température 2016-2021

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#23]

**Comment by vcameron1** [comment]
**Organisation des données pour l'injection**
---

- Création d'une view pour les requêtes de ce type de campagnes
- Schéma coleo :
	- Campaigns
		* Landmarks
		* Thermographs
	- landmark_id, thermograph_no, depth, height, is_on_bag, shading, notes
		* Observations
	- date_obs, time_obs, thermograph_id, campaign_id, is_valid, 
		* Obs_thermographs
	- obs_id, Temperature, Pressure, water_depth (?)
- Une campagne = un site (lac), comprend tous les thermographs
- Un repère pour l'ensemble des thermographs sur la chaine / un autre pour le thermograph hors de l'eau

**Comment by vcameron1** [comment]
Qiuelques sites prêts à injecter, d'autres ont encore besoin d'être saisi dans les gabarits

**Comment by vcameron1** [comment]
Troubles d'injection via RStusdio.biodiversite-quebec.ca

```r
Error:
! Failed to connect to coleo.biodiversite-quebec.ca port 443: Connection refused
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by vcameron1** [comment]
Comprend les inventaires se terminant en 2022
