### ISSUE TITLE
Physicochimie_terrain 2016 à 2021

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#24]
Physicochimie en lac, section terrain

**Comment by anouksimard** [comment]
LA physico terrain est prête je pense.

**Comment by poini5** [comment]
Bonjour,

Oui, les données de l'indicateur physicochimie de l'eau concernant les profils (température, oxygène, pH, conductivité et turbidité) sont recueillies et formater pour 2016 à 2020. Un fichier semblable au template d'injection habituel est créé et devrait être partagé sur le SharePoint sous-peu. Nous attendons des confirmations des différents partenaires terrains concernant les facteurs environnementaux de campagnes ainsi que pour des information sur les techniciens de campagnes.

Le formatage des données de physicochimie de type labo est aussi en cours, mais non complété. 

Bonne journée!

**Comment by poini5** [comment]
Une relance des régions a été effectuée cette semaine. Après le retour des 5 régions manquantes, les données du volet « profil » (température, oxygène, pH, conductivité et turbidité) de l'indicateur physicochimie seront formatées et prêtes à être transférées dans un template d'injection.

**Comment by poini5** [comment]
Pour ce qui est du volet « chimique » de la physicochimie (avec tests de laboratoire: COD, NH3, NOx, Ntot, PT, Chlo-a, Pheo-a), les données de 2018 à 2021 sont formatées et prêtes à être intégrées dans une template d'injection. Une rencontre avec le MELCC a dévoilé que les données de phosphore total sont aberrantes pour les années antérieures à 2018. Une correction de cette erreur est prévue de débuter en janvier 2023 par le MELCC.

**Comment by vcameron1** [comment]
Les inventaires pour la physicochimie ont été divisés en 2 campagnes distinctes : physicochimie_terrain et physicochimie_labo

## physicochimie_terrain

Différentes mesures de conductivité ... À éclaircir

## physicochimie_labo

Données à saisir dans le gabarit

**Comment by vcameron1** [comment]
Injecté le 3 mars 2023

## Corrections apportées aux données
- Renommer la colonne obs_lake_pH par obs_lake_ph
- Remove non breaking spaces and replace them with normal spaces
