### ISSUE TITLE
Insectes du sol 2021

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#25]

**Comment by francis-lessard** [comment]
Les données ont été exportées de ArcGIS Online (AGOL). Les données n'ont pas été revisitées, donc il reste des erreurs de saisies. Les données ont été envoyé à Pierrick Bloin. Il tri les échantillons et s'occupe d'identifier la partie carabe des échantillons. Une partie du fichier a également été envoyé à Annie Hibbert. De son côté, Annie s'occupe d'identifier les araignées et de valider certaines identifications de Pierrick. Une fois que Pierrick aura terminé de compléter le fichier, je débuterai les étapes de nettoyage. J'ajouterai les données d'Annie par la suite. 

Le premier fichier extrait: "Insecte_Sol_22oct2021" est le fichier de données brute avec traitement de base pour guider Pierrick dans son tri.

**Comment by francis-lessard** [comment]
Le nettoyage des données a été réalisé est disponible sous le nom : "Insecte_Sol_11mars2022_N1". Le fichier "Insecte_Sol_22oct2021 est maintenant dans le dossier brute. Le document "Insecte_Sol_11mars2022_N1" regroupe les identifications que Pierrick Bloin a réalisé sur les carabes. J'ai envoyé à Annie Hibbert le fichier contenant les identifications de Pierrick ainsi que les spécimens de carabes pour que celle-ci puisse les valider. D'autre part, j'ai également fait parvenir les gastéropodes à identifier à Angélique Dupuch ainsi que le fichier de saisie.

**Comment by anouksimard** [comment]
en attente de la taxonomiste prévu mi-octobre

**Comment by francis-lessard** [comment]
**Données Escargots & Limaces**
On va devoir s’asseoir de nouveau avec Angélique pour clarifier nos besoins et revoir les intérêts de leur envoyer des échantillons. J’avais fait une vidéo explicative de ce qu’on voulait qu’ils fassent avec les échantillons (j’ai perdu cette vidéo avec la migration de mon ordi). Clairement, ils n’ont pas compris. Au final, aucune espèce n’a été identifiée. Il y a seulement eu validation que c’était des arionidées ou non et comptage de seulement quelques échantillons…


**Données Araignées**
Annie désirait revisiter certaines identifications qu’elle avait faites dans le passé. Je lui ai donc transmis le fichier des données d’araignées de 2016 à 2020. Les modifications à faire dans COLEO se trouvent dans le fichier « Modif_COLEO ». Je vais contacter Victor pour qu’il fasse les modifications avec ce document. 

Pour les données 2021, j’ai corrigé plusieurs petites coquilles que Annie a faites dans son document final. Il y avait des noms d’auteur qui n’était pas standardisé. Il y avait des fautes de frappe sur des espèces. J’ai fait les correctifs. Il y a des spécimens qui sont notés « nr ». Annie m’a expliqué que c’est le diminutif de « near ». Elle a envoyé les spécimens notés « nr » à Simon Paradis et/ou Pierre Paquin pour validation.

**Données Carabes**
Puisque Pierrick était notre trieur ainsi que celui qui identifiait les carabes, le fichier contenant les identifications de Pierrick contient l’ensemble des données de tri. C’est-à-dire que tous les groupes taxonomiques ci-trouvent, mais qu’uniquement les carabes sont identifiés dans ce fichier. Le dernier fichier qu’a fourni Pierrick a été modifié pour contenir les correctifs de Annie. Pierrick avait fait une boîte de spécimens à faire valider par Annie et l’identification de quelques spécimens a été corrigée. 

À noter, le fichier d’identification de Annie et de Pierrick ne sont pas fusionné dans un seul fichier. 

Mis à part les données notées « nr », les données 2021 pourraient être converties au format COLEO et être injectées

**Comment by francis-lessard** [comment]
@vcameron1 
Après quelques échanges de courriels, nous arrivons à s'entendre que nous pouvons injecter les données même si 6 spécimens d'araignées ne sont pas encore identifiées. Nous avons établi que l'indentification des spécimens incertains seront identifiés moins précisément pour l'instant. Lorsque les taxonomistes auront terminés leur travail nous pourrons préciser l'identification de ces 6 spécimens. L'incertitude de l'identification de ces spécimens est visible dans le document "Unknown_specimen_review2022" ici: \\sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Insectes_Sol\Retour_Taxonomiste\Annie_Christie_Hibbert\2021\Brute

@Lauramilliard 
Les données sont prêtes à être injectées mais elles sont séparées en deux fichiers.

Tu peux retrouver les identifications d'araignées dans le fichier intitulé "Insecte_Sol_Araignee_V11_SitesFinale_2023mai16_Correction_Simon_Paradis" ici: \\sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Insectes_Sol\Retour_Taxonomiste\Annie_Christie_Hibbert\2021

Tu peux retrouver les identifications de carabes et tous les autres spécimens dans le fichier intitulé "Insecte_Sol_16mai2023_Tout_Sauf_Araignee" ici: \\sebsecu\INVENTAIRE\suivi de la biodiversité\Données_Indicateurs_Partage\Insectes_Sol\Retour_Taxonomiste\Pierrick_Bloin\2021

**Comment by vcameron1** [comment]
## À valider

- [ ] Campagne datée de 2018 avec observations en 2019 et date de récolte en 2021...

**Comment by francis-lessard** [comment]
@vcameron1 
Est-ce que tu peux nous donner le ou les numéros de spécimens problématiques à valider?
Merci!

**Comment by Lauramilliard** [comment]
Problème résolu , les commentaires dans les données ont été clarifiés : pot de récolte égaré lors de l'année 2018, retrouvé en 2019 et identifié en 2021 (étiquette écrite à la main). C'était pour Inukjuak (57_156_T01) pièges MP-020, MP-021 et MP-029.

**Comment by vcameron1** [comment]
- [ ] Les données sont en révision pour l'ajout du genre au nom taxonomique des espèces.

**Comment by vcameron1** [comment]
Données injectées
