### ISSUE TITLE
Papillons 2016-2020

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#3]

**Comment by Sckende** [comment]
Bonjour à vous,
est-ce que tout va bien ? Je ne vois pas de sujet à l'issue qui a été ouverte ?

**Comment by glaroc** [comment]
@Sckende Salut! On organise les campagnes injectées dans Coléo. C'est pourquoi ton nom a été assigné à certaines données, mais rassure-toi, tu n'as rien à faire :-)

**Comment by vcameron1** [comment]
Correction des sites 127_116_H01, 127_116_H02, 127_116_F01  à 126_116.
