### ISSUE TITLE
Orthoptères 2016-2020

### ISSUE THREAD

**Issue by anouksimard** [ReseauBiodiversiteQuebec/Coleo_DB#32]
Il faut ajouter le nom français et Anglais.
Il est important de mettre toujours le même nom de technicien pour une même campagne, et c'est dans observateur qu'on ajoute qui a pris l'échantillons. Si ce n'est pas pas écris voir les étiquettes.

**Comment by anouksimard** [comment]
@poini5 merci de penser à a enlever le nom d'orgine des noms latin

**Comment by vcameron1** [comment]
***Modifications faites au jeu de données pour l'injection***

- Sites 127_116 ont été changés pour 126_116
- Les campagnes ont été regroupées.
> Une campagne regroupe un effort d'échantillonnage et toutes les observations recueillies.
> Toutes les séquences analysées n'ont pas à être injectées ; Une ligne = une observation ou une campagne vide (pas une séquence analysée).
> J'ai retiré les séquences sans observations superflues.
> Une campagne se déroule sur une seule journée.
- J'ai converti les dates doivent dans un format texte.
- Correction de la variable d'observation : "présence" et pas "presence".
- J'ai ajusté les efforts : l'effort est pour l'ensemble de la campagne (1 effort par campagne).
> L'effort est indépendant de l'appareil. Le jeu de donnéescontient une ligne par séquence analysée.
> Effort = nb séquences analysées * 10 mins.
- J'ai formater campaigns_technicians en une liste

***Notes***
- Dans un chiffrer Excel, il vaut mieux laisser les cases sans valeur vides plutôt que de mettre NA
