### ISSUE TITLE
Température eau en Lac 2016-2021

### ISSUE THREAD

**Issue by francis-lessard** [ReseauBiodiversiteQuebec/Coleo_DB#40]
Les données ont été exportées de ArcGIS Online (AGOL). Les cases "autre" ont été éliminées. Les données ont été revisitées afin d’éliminer les erreurs de saisies. Selon notre tableau à l'interne, il manquerait les données des sites suivants: Témiscamingue (B) - 103_85; Tapini-Antoine-Labelle (D) - 122_94; Matawinie (C) - 127_99; Matawinie (D) - 128_100; Parc de la Mauricie - 134_101; Lac à la Tortue - 135_101; Sept-Rivières (C) - 137_144; Bellechasse (A) - 141_108; Rivière-du-Loup (B) - 142_120; Le Granit (A) - 148_101. Il faut investiguer pour ces sites. Est-ce qu'il y a eu des chaines de thermographes qui ont été installé ou enlevé dans ces sites en 2021?

**Comment by vcameron1** [comment]
Les données sont extraites manuellement des enregistreurs sous format CSV (originellement HOBO).

**Comment by vcameron1** [comment]
**Organisation des données pour l'injection**
---

- Création d'une view pour les requêtes de ce type de campagnes
- Schéma coleo :
	- Campaigns
		* Landmarks
		* Thermographs
	- landmark_id, thermograph_no, depth, height, is_on_bag, shading, notes
		* Observations
	- date_obs, time_obs, thermograph_id, campaign_id, is_valid, 
		* Obs_thermographs
	- obs_id, Temperature, Pressure, water_depth (?)
- Une campagne = un site (lac), comprend tous les thermographs
- Un repère pour l'ensemble des thermographs sur la chaine / un autre pour le thermograph hors de l'eau
