### ISSUE TITLE
caméra mammifère 2016-2020

### ISSUE THREAD

**Issue by anouksimard** [ReseauBiodiversiteQuebec/Coleo_DB#41]

**Comment by vcameron1** [comment]
Les caméras prennent 3 photos à intervalle d'une seconde lorsqu'elles sont déclenchées par détection de mouvement. Une seule de ces observations doit être gardée dans les données, sans quoi il y a pseudoréplication.

**Comment by Lauramilliard** [comment]
**Étapes de nettoyage et particularités du jeu de données**

Les données à injecter sont composées des détections d’espèce (observations) par caméra dans les différents sites, selon deux méthodes (time lapse et mouvement). Chaque ligne correspond à la détection d’un ou plusieurs individus sur une même photo. L’abondance de chaque individu détecté se retrouve dans le jeu de données. 

Les données brutes contiennent l’ensemble des photos prises par time lapse et par mouvement, pour tous les sites. Les photos sont d’abord triées afin de garder seulement les détections. La colonne « File » du fichier brute qui contient le nom des fichiers .JPG est incluse dans le jeu de données final et servira dans la colonne « media_name » afin de lier la photo à l’observation.

Les photos en mode mouvement ont été filtrées de sorte qu’une photo corresponde à une détection. La caméra prend jusqu’à 4 photos consécutives lors d’une détection de mouvement, la même observation est donc répliquée plusieurs fois. Après la prise de ces photos, la caméra ne fonctionne plus pendant 5 minutes. Conséquemment, nous avons conservé une seule photo pour chaque séquence de 4 photos prises à l’intérieur d’un intervalle de 5 minutes.

Afin de différencier les campagnes de time lapse et de mouvement, deux types d’effort sont calculés. Tout d’abord, nous calculons le temps (minutes) pendant lequel une caméra a fonctionné pour la méthode de détection par mouvement. Ces données se retrouvent dans la colonne « efforts_recording_minutes ». L’effort de la méthode par time lapse est calculé selon le nombre de photo prises entre le début et la fin de la campagne, retrouvé dans la colonne « efforts_photo_count ». 

Les données relatives à l’installation des appâts et des caméras sont également dans le jeu de données (le nom d’espèce des essences sur lesquelles il y a l’installation, leur azimut et dbh, hauteur de la caméra, coordonnées géographiques des appâts et caméras, ainsi que les dates d’installation de chacun). Il y a une duplication des colonnes repères (caméras et multiples appâts), chaque appât est numéroté dans le nom de la colonne (ex. lures_lure_1, lures_lure_2).
