### ISSUE TITLE
Localisations des sites 2015-2021

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#48]

**Comment by vcameron1** [comment]
Le nom des cellules doit être mis à jour. Certaines cellules au nom long ont maintenant des noms plus évocateurs pour les remplacer.

**Comment by vcameron1** [comment]
Les cellules et sites requis pour les campagnes insectes_sol et acoustique ont été injectés en février et avril 2022. Par contre, les autres n'ont pas été injectés.
