### ISSUE TITLE
Odonates 2016-2021

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#5]

**Comment by poini5** [comment]
Le template pour les odonates 2016-2020 est sur le point d'être complété. Il ne manque que quelques données terrains afin de discerner les différents observateurs par site. Les données 2021 sont aussi en traitement et seront possiblement envoyées en même temps pour injection.

**Comment by vcameron1** [comment]
# Quelques corrections au jeu de données

Le jeu de données initial contient quelques erreurs. Ces erreurs et leurs corrections sont décrites ici-bas. La correction des données a été fait dans le script [ReseauBiodiversiteQuebec/injection_notes/injection_odonates_2015-2020.R](https://github.com/ReseauBiodiversiteQuebec/injection_notes/odonates/injection_odonates_2015-2020.R)

## Les noms ne doivent pas contenir d'accents

Certains noms contiennent des accents

```
names_to_change <- c("André-Anne Tremblay" = "Andre-Anne Tremblay",
                    "Joëlle Spooner" = "Joelle Spooner",
                    "Jessica Dubé" = "Jessica Dube",
                    "Véronique St-Hilaire" = "Veronique St-Hilaire",
                    "Véronique Dion-Larivière" = "Veronique Dion-Lariviere")
```

## Le nom des observateurs doit être écrit au long

Le jeu de données ne contient que les initiales. Aussi, l'observateur doit être parmi les techniciens.

```
init_to_change <- c(
    "CD" = "Caroline Dube",
    "PAD" = "Pierre-Alexis Drolet",
    "NA" = NA,
    "EMT" = "Emilie Trepanier",
    "GT" = "Guillaume Tremblay",
    "SG" = "Serge Gauthier",
    "SS" = "Serge Gauthier",
    "AR" = "Ariel Ferland-Roy",
    "MEL" = "Marie-Eve Lessard",
    "LEP" = "Louis-Etienne Picard",
    "ADL" = "Louis-Etienne Picard",
    "OCT" = "Olivier C. Trudel",
    "JC" = "Jocelyn Caron",
    "CL" = "Christine Lambert",
    "DP" = "Daniel Potvin Leduc",
    "NT" = "Nathalie Tessier",
    "LV" = "Lucie Veilleux",
    "GC" = "Gabriel Chabot",
    "AAT" = "Andre-Anne Tremblay",
    "DG" = "Daniel Girard",
    "SH" = "Shany Houde",
    "DH, JD" = "Denis Henri, Jessica Dube",
    "VSTH" = "Veronique St-Hilaire",
    "KQP" = "Kevin Quirion-Poirier",
    "ED"= "Emilie Dorion",
    "JT" = "Jacques Tremblay",
    "JMV" = "Jean-Marc Vallieres",
    "JFH" = "Jean-Francois Houle",
    "CG" = "Camille Guay",
    "ID" = "Isabelle Dumais",
    "AG" = "Alexane Gaudet",
    "JM" = "Jasmin Michaud",
    "PL" = "Patrick Lacerte",
    "TC" = "Thomas Castonguay",
    "KS" = "Karen Savard",
    "AP" = "Alexandre Paiement",
    "MCB" = "Maude Coté-Bedard",
    "JS" = "Joelle Spooner",
    "ML" = "Martine Lavoie",
    "RP" = "Rosaly Plamondon",
    "JD" = "Jessica Dubé",
    "VSH" = "Veronique St-Hilaire",
    "MM" = "Mariane Moffat",
    "SB, WR" = "Sonia Boudreault, William Rondeau",
    "LA" = "Louvik Archambault",
    "AB" = "Andreanne Beauchemin",
    "JL" = "Juliette Larivee",
    "LT" = "Louise Tremblay",
    "EG" = "Emilie Grenier",
    "VDL" = "Veronique Dion-Lariviere",
    "SN" = "Sylvie Normand",
    "ES, FG" = "Eric Savard, Francois Girard",
    "JPB" = "Jean-Philippe Baillargeon",
    "LB" = "Lysandre Bourgouin",
    "DD" = "Denis Desjardins",
    "ND" = "Naomie Dontigny",
    "LP" = "Laurianne Plante",
    "FMC, FL" = "Felix Maheu Coutu, Francis Lessard",
    "MAD" = "Marc-Antoine Dorval")
```

## Les colonnes extra sont constitués d'une variable, d'une valeur, d'un type et d'une description

La nouvelle template contiendra ces colonnes et décrira ce qu'ils contiennent.

## Les commentaires sur les observateurs vont en note dans la table observations

```
observations_notes = 'Commentaires sur les observateurs'
```

## Pour les campagnes vides, on donne la valeur de NA aux autres colonnes que celles des tables campaigns, environments, landmarks

## Les dates doivent être dans le format YYYY-MM-DD

**Comment by glaroc** [comment]
Note que techniquement, il n'y a aucun problème avec les accents dans les noms.

**Comment by vcameron1** [comment]
Correction des sites 127_116_H01, 127_116_H02, 127_116_F01  à 126_116.

**Comment by poini5** [comment]
[Intranet logo]
Merci Victor,

Je tiendrai compte de ces correctifs à l'avenir.

Bonne journée

Nicolas
________________________________
De : Victor Cameron ***@***.***>
Envoyé : 8 juin 2022 19:13
À : ReseauBiodiversiteQuebec/Coleo_DB ***@***.***>
Cc : Poirier, Nicolas (DEFTHA) ***@***.***>; Assign ***@***.***>
Objet : Re: [ReseauBiodiversiteQuebec/Coleo_DB] Odonates 2016-2021 (Issue #5)


Quelques corrections au jeu de données

Le jeu de données initial contient quelques erreurs. Ces erreurs et leurs corrections sont décrites ici-bas. La correction des données a été fait dans le script ReseauBiodiversiteQuebec/injection_notes/injection_odonates_2015-2020.R<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FReseauBiodiversiteQuebec%2Finjection_notes%2Fodonates%2Finjection_odonates_2015-2020.R&data=05%7C01%7CNicolas.Poirier%40mffp.gouv.qc.ca%7C8fdbc8b319dc4439e99c08da49a47d2f%7C8705e97737814f4790e1c84c8b884da1%7C0%7C0%7C637903268073602067%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E8twM7tU7jVJJd%2F6o90y3q2dcrsy3kPlyC3KSYb08Y8%3D&reserved=0>

Les noms ne doivent pas contenir d'accents

Certains noms contiennent des accents

names_to_change <- c("André-Anne Tremblay" = "Andre-Anne Tremblay",

                    "Joëlle Spooner" = "Joelle Spooner",

                    "Jessica Dubé" = "Jessica Dube",

                    "Véronique St-Hilaire" = "Veronique St-Hilaire",

                    "Véronique Dion-Larivière" = "Veronique Dion-Lariviere")



Le nom des observateurs doit être écrit au long

Le jeu de données ne contient que les initiales. Aussi, l'observateur doit être parmi les techniciens.

init_to_change <- c(

    "CD" = "Caroline Dube",

    "PAD" = "Pierre-Alexis Drolet",

    "NA" = NA,

    "EMT" = "Emilie Trepanier",

    "GT" = "Guillaume Tremblay",

    "SG" = "Serge Gauthier",

    "SS" = "Serge Gauthier",

    "AR" = "Ariel Ferland-Roy",

    "MEL" = "Marie-Eve Lessard",

    "LEP" = "Louis-Etienne Picard",

    "ADL" = "Louis-Etienne Picard",

    "OCT" = "Olivier C. Trudel",

    "JC" = "Jocelyn Caron",

    "CL" = "Christine Lambert",

    "DP" = "Daniel Potvin Leduc",

    "NT" = "Nathalie Tessier",

    "LV" = "Lucie Veilleux",

    "GC" = "Gabriel Chabot",

    "AAT" = "Andre-Anne Tremblay",

    "DG" = "Daniel Girard",

    "SH" = "Shany Houde",

    "DH, JD" = "Denis Henri, Jessica Dube",

    "VSTH" = "Veronique St-Hilaire",

    "KQP" = "Kevin Quirion-Poirier",

    "ED"= "Emilie Dorion",

    "JT" = "Jacques Tremblay",

    "JMV" = "Jean-Marc Vallieres",

    "JFH" = "Jean-Francois Houle",

    "CG" = "Camille Guay",

    "ID" = "Isabelle Dumais",

    "AG" = "Alexane Gaudet",

    "JM" = "Jasmin Michaud",

    "PL" = "Patrick Lacerte",

    "TC" = "Thomas Castonguay",

    "KS" = "Karen Savard",

    "AP" = "Alexandre Paiement",

    "MCB" = "Maude Coté-Bedard",

    "JS" = "Joelle Spooner",

    "ML" = "Martine Lavoie",

    "RP" = "Rosaly Plamondon",

    "JD" = "Jessica Dubé",

    "VSH" = "Veronique St-Hilaire",

    "MM" = "Mariane Moffat",

    "SB, WR" = "Sonia Boudreault, William Rondeau",

    "LA" = "Louvik Archambault",

    "AB" = "Andreanne Beauchemin",

    "JL" = "Juliette Larivee",

    "LT" = "Louise Tremblay",

    "EG" = "Emilie Grenier",

    "VDL" = "Veronique Dion-Lariviere",

    "SN" = "Sylvie Normand",

    "ES, FG" = "Eric Savard, Francois Girard",

    "JPB" = "Jean-Philippe Baillargeon",

    "LB" = "Lysandre Bourgouin",

    "DD" = "Denis Desjardins",

    "ND" = "Naomie Dontigny",

    "LP" = "Laurianne Plante",

    "FMC, FL" = "Felix Maheu Coutu, Francis Lessard",

    "MAD" = "Marc-Antoine Dorval")



Les colonnes extra sont constitués d'une variable, d'une valeur, d'un type et d'une description

La nouvelle template contiendra ces colonnes et décrira ce qu'ils contiennent.

Les commentaires sur les observateurs vont en note dans la table observations

observations_notes = 'Commentaires sur les observateurs'



Pour les campagnes vides, on donne la valeur de NA aux autres colonnes que celles des tables campaigns, environments, landmarks
Les dates doivent être dans le format YYYY-MM-DD
