### ISSUE TITLE
Odonates 2022

### ISSUE THREAD

**Issue by francis-lessard** [ReseauBiodiversiteQuebec/Coleo_DB#63]
Manquant:
Kangiqsualujuaq - 90_189; Manque TOUT (Contacté)

Post-traitement:
(Aucun restant)

Fait:
Mont-Orford - 144_96; Manque labo tourbiere (FAIT, mais pas de photo)
Parc Frontenac - 145_102; uniqument labo (FAIT)
Grande-Vallée - 148_144; uniquement labo (FAIT)
Hereford - 148_96; uniquement labo (FAIT)
Pointe-aux-Outardes - 137_131; doublon terrain (Corrigé)
Kuujjuaq - 86_180; uniquement terrain (FAIT)
Cambrien - 94_168; Manque TOUT (FAIT)
Parc du Lac-Témiscouata (B) - 143_122; Manque TOUT (FAIT)
Parc du Fjord-du-Saguenay - 135_119; Manque le formulaire labo/entrepot (Fait par Francis Lessard)
Parc de la Mauricie - 133-101; Manque le formulaire labo/entrepot (FAIT)
La Côte-de-Beaupré - 139_111; doublon de terrain et de labo; Ils ont rempli 2 fois le formulaire chacun leur tour avec leur propre capture. Il faudra fusionner les données durant le nettoyage. (FAIT)
La Côte-de-Beaupré - 139_111; Changer H02 pour H01 (FAIT)
Mont-Orford - 144_96; Changer tourbière (H02) pour tourbière (H01) (FAIT)
Parc Kuururjuaq - 94_192; Changer marais (H02) pour marais (H01) (FAIT)

Marais et Tourbière pour:
-------------------------
La Jacque-Cartier - 137_107
Mont Orford - 144_96
Montmagny (A) -142_111
Pointe-platon -138_105
Parc Kuururjuaq - 94_192

**Comment by vcameron1** [comment]
Modifications à apporter au gabarit d'injection

- [ ] Retrait des colonnes supplémentaires
- [ ] Retrait des lignes avec des NA
- [ ] Correction du nom de colonne "obs species_taxa_name" à "obs_species_taxa_name"
- [ ] Conversion des colonnes de date en format texte
