### ISSUE TITLE
Insectes du sol 2016-2020

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#7]
Étape de Nettoyage

Félix couture Maheu a pris les informations dans V7 du SharePoint ainsi que des informations dans le Z : provenant d’identification des trieurs. Dans V7, il y avait deux types de données. Des données triées (Carabe_Tri) et des données d’espèces identifiées (Carabe_ID). Félix a fusionnée les deux fichiers.

Le fichier fusionné fonctionne en deux étapes. Le trieur identifiait toutes les fioles dans la colonne groupe_taxonomique pour ensuite l’éclater en plusieurs lignes lors de l’identification. Ainsi, au premier tour il pouvait identifier 25 araignées dans un échantillon en premier lieu. Puis en second lui, la ligne contenant 25 araignées pouvaient s’éclater en plusieurs autres lignes dépendamment du nombre d’espèces au sein du groupe de 25.

Une fois la fusion faite, je dois adapter le fichier pour être injecté dans le format de Coleo. J’ai ajouté la colonne « rank » afin d’identifier le niveau taxonomique auquel on se réfère avec la colonne « groupe_taxonomique ». J’ai éliminé la colonne « sp_autre » qui comptabilise les identifications qui ne sont pas dans la liste de choix prédéfinit. J’ai ajouté la date de pose afin d’avoir la période à laquelle les pièges étaient actifs. J’ai ajouté le nom des techniciens qui ont été sur le terrain ainsi que le nom des identificateurs et validateurs qui ont été fusionné dans la même colonne. Mollusque est devenu gastéropode. Les larves, les inconnus et les autres sont devenus juste Insecta. J’ai ajouté la note larve pour les insectes qui sont des larves. Il y avait des aphides et des pucerons qui sont la même chose, j’ai mi que des pucerons. Idem pour puce et Siphonapteres, j’ai gardé puce. J’ai d’ailleurs changé phalangidae pour phalangiidae. Il y avait des millespattes et des millipede je les ai fusionnés sous les millespattes. J’ai changé le nom des colonnes pour me fier à la colonne présente dans Coleo. J’ai ajouté la colonne type contenant « insecte_sol ». 

Ensuite, nous avons décidé finalement de faire deux formats de données. Un format plus détaillés pour la consultation interne des données : « Insectes_Sol_Donnees_2016-2021 ». Puis un format très épuré et résumé pour l’injection des données : « Insectes_Sol_Injection ». Dans cette dernière version, j’ai éliminé la colonne « recolte ». J’ai fusionné la colonne « identificateur » avec la colonne « technicians ». J’ai éliminé « groupe_taxonomique », « famille », « genre » et « espece ». 

Rendu à l’injection, nous nous sommes rendu compte que les coordonnées n’étaient pas présentes dans les données. Laura Milliard et moi avons donc travaillé à ajouter les coordonnées de chaque piège avec un code R. Finalement, le fichier détaillé ne contient pas les coordonnées et le fichier résumé pour l’injection possède les coordonnées. Plusieurs données non complètes ont été retirées du fichier résumé, mais conservé dans le fichier détaillé. 

Document détaillé : « Insectes_Sol_Donnees_2016-2020 »
Document résumé : « Insectes_Sol_Injection_VF »

**Comment by francis-lessard** [comment]
Pour Marie-Pierre,
Les données sont prêtes à être injecter. Je n'ai pas vu le profil de Victor dans Git hub. J'aurais voulu assigner à lui donc par défaut je t'ai assigné la suite. Tu pourras lui faire le relais j'imagine. Le lien du fichier à injecter ce trouve dans le tableau. Le lien amène dans le sharepoint. Est-ce que ça va dans le sharpoint ou on voulait uploader les fichiers à injecter directement dans Github? Si c'est dans Gthub, comment je fais pour uploader ledit fichier?
Merci!

**Comment by vcameron1** [comment]
Some things to check when data will first be uploaded

Column names are correct and match the reference table?
- name_ref_species --> taxa_name
- name_cells --> nom_cellule
- type_campagne --> camp_type
- type_sites --> site_types

Other considerations
- lat/lon à transformer en géométrie 
- Techniciens à diviser ou à laisser en array?
- Colonne site_name à ajouter?
- Colonne category pour la table taxa à ajouter?

Questions
- opened_at et closed_at correspond à la campagne? au date_samp de la table sample ? à la table sites?

**Comment by francis-lessard** [comment]
@vcameron1: À qui son assigné tes questions/things to check?
Personnellement, je crois que @glaroc est plus apte à pouvoir répondre à toutes les questions autour de Coleo puisque ma compréhension est assez limité à ce niveau. Parc contre, j'aurais tendance à croire que "opened_at" et "closed_at" est relié à la table "campaigns".

**Comment by glaroc** [comment]
Les opened_at et closed_at sont parfois utilisés pour la date d'ouverture du site, à la date du début de la campagne, à la date de l'échantillon (pour les campagnes qui utilisent le concet d'échantillons) et/ou à la date de l'observation. Ça peut potentiellement être la même date partout si tout s'est fait la même journée. Il faut juste "mapper" ces dates aux bonnes colonnes lors de l'insertion.

**Comment by vcameron1** [comment]
@francis-lessard ces questions/considérations sont des notes pour Andrew et moi en vue de l'injection des données que nous ferons plus tard aujourd'hui. Ce n'est peut être pas la meilleure plateforme où laisser ces commentaires?

**Comment by francis-lessard** [comment]
@vcameron1 Non, ça va. Peut-être juste ajouter une note la prochainement fois comme ça on va être sur si c'est une question qui est adressé ou une note.

**Comment by vcameron1** [comment]
Quelques détails à regarder ensemble avant d'injecter les données
@francis-lessard @aammd 

Les nom de colonnes sont à standardiser. Voir [rcoleo::coleo_get_name_table()](https://github.com/ReseauBiodiversiteQuebec/rcoleo/blob/vic/R/coleo_get_name_table.R) pour les noms de colonnes que je propose. Nous pourrons en discuter. Voici certaines modifications à apporter :
- [ ] type_campaign -> campaign_type
- [ ] name_ref_species -> ref_taxa_name
- [ ] diviser la colonne value_abondance en deux: observation_variable et observation_value
- [ ] technicians -> campaign_technician_1
- [ ] rank -> ref_taxa_rank

Des précisions doivent être apportées sur certaines données :
- [ ] lat_trap/lon_trap correspond à la localisation du "landmark ? Si oui, renommer land_lat/land_lon
- [ ] insérer lat/lon avec un nombre à virgules. Présentement, lat_trap/lon_trap n'ont pas tous le même nombre de "digits": lat range = -76311209 à -655
- [ ] opened_at/closed_at correspond aux dates d'ouverture et de fermeture de la campagne ? Si oui, renommer campaign_date_opened/campaign_date_closed
- [ ] le format actuel des noms de techniciens font en sorte que tous les noms seront injectés comme étant un seul nom. eg. "Lucie_Veilleux,Nathalie_Tessier,Jessica_Turgeon". Solution, un nom par colonne avec les colonnes nommées campaign_technician_1, campaign_technician_2, etc
- [ ] la colonne notes correspond aux notes de la table observation, samples, ou autres? Renommer observation_notes/sample_notes/land_notes

Certaines colonnes sont manquantes au jeu de données pour qu'il soit injecté
- [ ] ajouter la colonne observation_date
- [ ] ajouter la colonne observation_is_valid
- [ ] ajouter la colonne ref_taxa_tsn
- [ ] ajouter la colonne observation_taxa_name (mêmes valeurs que name_ref_species)
- [ ] Question: n'avons-nous pas besoin de cell_code pour l'injection ?

Certaines colonnes actuellement présentes ne sont pas requises et doivent être retirées
- [ ] name_cells (les cellules sont injectées séparément)
- [ ] cell_id
- [ ] site_type (type_sites; les sites sont injectés séparément, seule la colonne site_code est requise)

Enfin, je n'ai fait aucune vérification/exploration des données en soi. L'ensemble de mes commentaires touche uniquement la forme du tableau de données à injecter.

**Comment by glaroc** [comment]
Je crois que plusieurs de ces modifications, comme le mapping des colonnes, doit se faire dans Rcoléo, et non dans le fichier d'origine. Des colonnes comme observation_is_valid peuvent juste être mise à True dans le script d'injection.

**Comment by vcameron1** [comment]
Note à nous même, le nom de certaines espèces sont à être confirmées puisqu'ils ne match pas à un tsn.

**Comment by glaroc** [comment]
Note que pour la végétation, on privilégie VASCAN
