### ISSUE TITLE
Acoustique Orthoptère 2021-2022

### ISSUE THREAD

**Issue by francis-lessard** [ReseauBiodiversiteQuebec/Coleo_DB#76]
Manquant
Baie de l'Île Verte; Manque TOUT (Dans le PASL; incertitude d'obtenir les données. En attente du fédéral. Demander à Caroline Dubé pour plus d'info)
Cap tourmente; Manque TOUT (Dans le PASL; incertitude d'obtenir les données. En attente du fédéral. Demander à Caroline Dubé pour plus d'info)
Kangiqsualujuaq - 90_189; Manque TOUT. Données récoltées, mais aucune nouvelle de leur part

Post-Traitement
Aucun restant

Problème avec les données
Aucun restant

Fait
Parc d'Opémican (B) - 106_80; manque retrait tourbiere et forestier (Fait)
Battures St-Augustin - 139_107; manque retrait marais (FAIT)
La Mitis - 144_129; manque le retrait tourbiere et forestier (FAIT)
Parc Frontenac - 145_102; manque retrait tourbiere (FAIT)
La Jacques-Cartier - 137_107; manque le retrait tourbiere et marais (Fait)
Matawinie (D) / Devenyns - 128_100; manque le retrait tourbiere (Fait)
Montmagny (A) - 142_111; manque le retrait tourbiere et marais (Fait)
L'Érable - 139_103; manque le retrait tourbiere (Fait)
Pointe-Platon - 138_105; manque retrait marais (Fait)
La Côte-de-Beaupré - 139_111; manque retrait tourbiere (Fait)
Parc du Lac Témiscouata - 143_122; manque installation et retrait forestier (Le site n'a pas été fait; données inexistantes)
Assinica - 107_115; manque retrait tourbière (FAIT)
Parc de la Mauricie - 133_101; manque retrait tourbiere (FAIT)
La Vallée-de-l'Or (E) / Lac Guégen - 109_95; manque le retrait tourbiere (FAIT)
Mont-Orford - 144_96; manque le retrait tourbiere, marais et forestier (Fait)
Parc du Fjord-du-Saguenay - 135_119; manque retrait forestier et tourbiere (Fait)
Lac Cambrien - 94_168; Doublon de retrait à supprimer (FAIT)
Kuujjuaq - 86_180; forestier changer pour toundrique (FAIT)
Batture St-Augustin - 139_107; changer H02 pour H03 (FAIT)
Vérifier que les numéros de site (H01, H02, etc.) concordent (FAIT)
Parc du Fjord-du-Saguenay - 135_119; Installation en marais (Fait, il n'y a pas de marais pour acoustique)
Hereford -148_96; voltage au début à 0 et à 0 à fin (FAIT)
La Mitis - 144_129; tourbière, ultrason à vérifier le numéro (FAIT)
Kuujjuaq - 86_180; ultrason à vérifier le numéro. Voltage pas bon (FAIT)
Assinica - 107_115; ultrason à vérifier le numéro. Batterie; information non pertinente (FAIT)

**Comment by francis-lessard** [comment]
@Lauramilliard 
Les données issues d'AGOL sont prêtes à être changé en format COLEO par contre
@CaroDube et @anouksimard 
Il y a des problèmes avec certaines entrées de données (voir plus haut). Il faudrait prendre une décision sur ces données avant de faire la conversion vers COLEO.

**Comment by vcameron1** [comment]
## Modifications à apporter en vue de l'injection


Heure

- [ ] Le message portant sur le format de l'heure est provoqué par les valeurs absentes (NA) dans les colonnes de temps (efforts_time_start, efforts_time_finish, etc)
- [ ] Lorsqu'un csv est utilisé plutôt qu'un gabarit, il faut s'assurer que les valeurs ne contenant pas de données (qui vallent NA) soient sauver comme étant vide. Autrement, les valeurs 'NA' son converties en caractères ("NA") et sa cause de problèmes pour l'injection. Il suffit d'ajouter `na = ""` à write.csv : `write.csv(df, "my_data.csv", na = "")`

Coquille

- [ ] La valeur contenue dans la colonne observations_extra_variable_1 (taxonomixt) doit être corrigée pour "taxonomist"

obs_species_taxa_name

- [ ] Commentaires : les commentaires doivent être retirés de la colonne obs_species_taxa_name et placés dans la colonne observations_notes. Les commentaires de la colonne obs_species_taxa_name doivent être remplacés par un nom scientifique, par exemple Insecta. Je suggère de prendre le nom scientifique du groupe décrit par le commentaire
- [ ] Commentaires : certains commentaires font référence à une absence d'observation, par exemple "No singing insect sound signal detected on recording". Il faut alors laisser les colonnes touchant l'observation vides. Voir onglet "README" du gabarit pour la marche à suivre
- [ ] Unknown : les valeurs Unknown ou Unknown Gomphorecinae, doivent être soit retirés ou remplacés par le nom d'un groupe taxonomique (eg. Gomphorecinae)
- [ ] Complexes : il y a des complexes, par exemple "Oecanthus nigricornis/pini/quadripunctatus" qui doivent être formatés selon la convention que nous avons établie ("Oecanthus nigricornis | Oecanthus pini | Oecanthus quadripunctatus")

Efforts

- [ ] Les séquences d'enregistrements écoutés par le taxonomiste constituent les efforts. Chaque séquence écoutée est un effort distinct. Est-il possible d'ajouter l'heure de début et l'heure de fin à la séquence analysée ? Autrement, chaque campagne ne contiendra qu'un seul effort de 10 minutes plutôt qu'une série d'efforts de 10 minutes puisqu'il n'y aura pas d'information pour différencier les différentes séquences/efforts.

Gabarit

- [ ] J'ai apporté quelques changements au gabarit en avril. Par exemple, j'ai retiré la colonne campaigns_notes pour diminuer les risques de duplication des campagnes. Je constate que la colonne est encore présente dans le csv que tu m'as fournis, mais je ne vois pas de décalage majeur entre le son format et celui du gabarit. Ça sera okkay pour cette fois
