### ISSUE TITLE
Gestion de l'utilisation des observations d'ADNe

### ISSUE THREAD

**Issue by vcameron1** [ReseauBiodiversiteQuebec/Coleo_DB#82]
Seules certaines observations d'ADNe doivent être utilisées. Les autres sont dupliquées ou improbables, donc à ne pas considérer dans les calculs taxonomiques.

Cette sélection d'observations doit être implantée aux calculs taxonomiques (taxa_richness, taxa_abundance et api.branch_tips). Vincent propose de l'implémenter directement sur la table obs_edna.

```
SELECT *
FROM campaigns, observations, obs_edna
WHERE campaigns.type = 'ADNe'
	AND observations.campaign_id = campaigns.id
	AND obs_edna.observation_id = observations.id
	AND trim(replace(extra::text, '\"', '"'), '"')::jsonb -> 'échelle_spatiale' ->> 'value' = 'lac'
        AND obs_edna.type_edna IN ('confirmé', 'probable')
```

**Comment by glaroc** [comment]
Donc on ferait une view ?

**Comment by vcameron1** [comment]
[cid:F1061752-CCD3-40B6-8849-80B0D93A60BA]

Le 2 nov. 2022 à 11:34, Guillaume Larocque ***@***.******@***.***>> a écrit :



Donc on ferait une view ?

**Comment by vincent-beauregard-ielab** [comment]
Comme recommandée @glaroc, nouvelle view créée : `obs_edna_likely`

Les fonctions `api.taxa_abundance` et `api.taxa_richness` ont été modifiées pour consommer les abondances et richesses à partir de cette view.

**Comment by glaroc** [comment]
Génial!
