### ISSUE TITLE
Physico-Chimie en lac 2022 - TERRAIN

### ISSUE THREAD

**Issue by vcameron1** [ReseauBiodiversiteQuebec/Coleo_DB#87]
Manquant
-
**TOUTES LES DONNÉES ONT ÉTÉ REÇUES**

Post-Traitement
-
(Voir problèmes avec les données)

Problème avec les données
-
Rivière-du-Loup (B) - 142_120: La physico et le zooplancton n'a pas été fait la même année. Est-ce que ça occasionne un problème dans COLEO pour l'ouverture et la fermeture de la campagne?

Fait
-
Grande-Vallée - 148_144; Manque TOUT (Fait)
Antoine-Labelle (E)/Montjoie - 126_92; Manque TOUT (Fait)
ZEC Saint-Patrice - 117_82; Manque TOUT (Fait)
Rivière-du-Loup(B) - 142_120; Manque les données, mais j'ai les échantillons (Fait)
Parc du Lac-Témiscouata (B) - 143_122; Manque les données de physico_chimie (Ne possédait pas de YSI, données inexistantes)
Parc du Fjord-du-Saguenay - 135_119; Manque les données de physico_chimie (Ne possédait pas de YSI, données inexistantes)
Fusionner le formulaire zooplancton et physico_chimie pour Akumunan, Antoine-Labelle (D), Hereford et La Côte-de-Beaupré (FAIT)
Parc d'Opémican - 106_80: Manque les données (Fait)
Rivière-du-Loup (B) - 142_120: Manque les données (Fait)
Parc Frontenac - 145_102: La physico-chimie est incomplète. Est-ce qu'on demande au personnel de la refaire?

> Après avoir discuter avec Caroline, non on ne fait pas reprendre la physico-chimie du lac.

**Comment by francis-lessard** [comment]
@vcameron1 
Est-ce que la création de cet onglet est une erreur? 
J'avais déjà créée un onglet "Physico-Chimie en lac 2022". Il faudrait simplement faire attention de ne pas créer de doublon.

**Comment by vcameron1** [comment]
@francis-lessard Les onglets ont été nettoyés. L'autre onglet tagué 'Physicochimie_terrain' est dans la colonne 'injecté' et comprend les données de 2016 à 2021.
